version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    env_file:
      - .env
    expose:
      - 8000
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - ../:/geodjango_proj/
    command: bash -c "python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgis/postgis:latest
    restart: on-failure
    volumes:
      - /usr/local/var/postgres:/var/lib/postgres/data/pgdata
    env_file:
      - .env.db
    ports:
      - 5432:5432
    expose:
      - 5432
